-- firmware_pkg.vhd — generated by asm.py, do not edit
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

package firmware_pkg is
    constant MEM_WORDS : integer := 1024;
    type bram_init_t is array(0 to MEM_WORDS-1) of std_logic_vector(31 downto 0);
    constant FIRMWARE : bram_init_t := (
        0 => x"00A00200",
        1 => x"01A00000",
        2 => x"01000001",
        3 => x"20080100",
        4 => x"588FFFF0",
        5 => x"200000FF",
        6 => x"01A00001",
        7 => x"20080200",
        8 => x"590FFFF4",
        9 => x"02000004",
        10 => x"5807FFD8",
        others => x"00000000"
    );
end package firmware_pkg;
