# cmod_a7.xdc — Titania / M56 constraints for Cmod A7-35T

# 12 MHz clock
set_property PACKAGE_PIN L17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 83.33 [get_ports clk]

# LEDs
set_property PACKAGE_PIN A17 [get_ports {led[0]}]
set_property PACKAGE_PIN C16 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]

# Buttons (active high — BTN0 = reset)
set_property PACKAGE_PIN A18 [get_ports {btn[0]}]
set_property PACKAGE_PIN B18 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]

# USB-UART via FT2232HQ
set_property PACKAGE_PIN J17 [get_ports uart_rxd_in]
set_property PACKAGE_PIN J18 [get_ports uart_txd_out]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd_in]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd_out]

# IS61WV5128BLL on-board SRAM
set_property PACKAGE_PIN M18 [get_ports {sram_addr[0]}]
set_property PACKAGE_PIN M19 [get_ports {sram_addr[1]}]
set_property PACKAGE_PIN K17 [get_ports {sram_addr[2]}]
set_property PACKAGE_PIN N17 [get_ports {sram_addr[3]}]
set_property PACKAGE_PIN P17 [get_ports {sram_addr[4]}]
set_property PACKAGE_PIN P18 [get_ports {sram_addr[5]}]
set_property PACKAGE_PIN R18 [get_ports {sram_addr[6]}]
set_property PACKAGE_PIN W19 [get_ports {sram_addr[7]}]
set_property PACKAGE_PIN U19 [get_ports {sram_addr[8]}]
set_property PACKAGE_PIN V19 [get_ports {sram_addr[9]}]
set_property PACKAGE_PIN W18 [get_ports {sram_addr[10]}]
set_property PACKAGE_PIN T17 [get_ports {sram_addr[11]}]
set_property PACKAGE_PIN T18 [get_ports {sram_addr[12]}]
set_property PACKAGE_PIN U17 [get_ports {sram_addr[13]}]
set_property PACKAGE_PIN U18 [get_ports {sram_addr[14]}]
set_property PACKAGE_PIN V16 [get_ports {sram_addr[15]}]
set_property PACKAGE_PIN W16 [get_ports {sram_addr[16]}]
set_property PACKAGE_PIN W17 [get_ports {sram_addr[17]}]
set_property PACKAGE_PIN V15 [get_ports {sram_addr[18]}]
set_property PACKAGE_PIN W15 [get_ports {sram_data[0]}]
set_property PACKAGE_PIN W13 [get_ports {sram_data[1]}]
set_property PACKAGE_PIN W14 [get_ports {sram_data[2]}]
set_property PACKAGE_PIN U15 [get_ports {sram_data[3]}]
set_property PACKAGE_PIN U16 [get_ports {sram_data[4]}]
set_property PACKAGE_PIN V13 [get_ports {sram_data[5]}]
set_property PACKAGE_PIN V14 [get_ports {sram_data[6]}]
set_property PACKAGE_PIN U14 [get_ports {sram_data[7]}]
set_property PACKAGE_PIN P19 [get_ports sram_oen]
set_property PACKAGE_PIN R19 [get_ports sram_wen]
set_property PACKAGE_PIN N19 [get_ports sram_cen]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports sram_oen]
set_property IOSTANDARD LVCMOS33 [get_ports sram_wen]
set_property IOSTANDARD LVCMOS33 [get_ports sram_cen]
