-- system.vhd — Titania M56 system top level for Cmod A7-35T
--
-- This is the "glue" file that connects the CPU, the program memory (Block RAM),
-- and the UART together into a complete system.
--
-- ─── Why VHDL ────────────────────────────────────────────────────────────────
--
-- VHDL and Verilog are the two dominant hardware description languages.
-- Verilog is more concise and forgives type mismatches with implicit
-- conversions. VHDL is more verbose but strict: every signal has an explicit
-- type, and the compiler rejects mismatches rather than silently converting
-- them. A width mismatch or a signed/unsigned confusion that Verilog would
-- quietly accept becomes a compile error in VHDL.
--
-- For a teaching machine, that strictness is a feature. The compiler teaches
-- you to think precisely about bit widths and signal types — habits that
-- matter in any serious hardware design. Verilog's convenience is also its
-- danger: bugs that would be caught at compile time hide until the hardware
-- misbehaves in ways that are very hard to diagnose.
--
-- VHDL is the language of choice in defence, aerospace, and industry
-- because exactness matters in such systems.
--
-- ─── What lives here ─────────────────────────────────────────────────────────
--
--   CPU (cpu.vhd)       — executes M56 instructions
--   Block RAM                — 1024 × 32-bit words of program/data memory,
--                         pre-loaded with echo.s firmware at synthesis time
--   UART (uart.vhd)    — sends and receives bytes over the USB-serial port
--
-- ─── Memory map ──────────────────────────────────────────────────────────────
--
--   Address bit 22 = 0  →  Block RAM  (0x000000 – 0x3FFFFF)
--   Address bit 22 = 1  →  UART  (0x400000)
--
--   This is the simplest possible address decode: a single bit.
--   0x400000 in binary is 0100 0000 0000 0000 0000 0000 — bit 22 is set.
--   Any Block RAM address has bit 22 = 0.
--
-- ─── UART register ───────────────────────────────────────────────────────────
--
--   Reading  0x400000 returns a 32-bit status word:
--     bit 9     = TX busy   (1 = transmitter is currently sending a byte)
--     bit 8     = RX valid  (1 = a byte has arrived and is waiting to be read)
--     bits 7..0 = received byte
--
--   Writing  0x400000 sends a byte:
--     bits 7..0 = byte to transmit
--
-- ─── Physical pins ───────────────────────────────────────────────────────────
--
--   BTN0 (nearest USB) = reset   — hold to reset CPU, release to run
--   LED0               = RX valid (briefly lights when a byte arrives)
--   LED1               = TX busy  (lights while the UART is sending)

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use work.firmware_pkg.ALL;   -- auto-generated by asm.py; contains FIRMWARE constant
use work.board_pkg.ALL;      -- board/cmod_a7.vhd: clock frequency, baud rate, Block RAM size

entity SOC is
    port (
        clk          : in  STD_LOGIC;                      -- 12 MHz from Cmod A7
        uart_rxd_in  : in  STD_LOGIC;                      -- serial data in  (from PC)
        uart_txd_out : out STD_LOGIC;                      -- serial data out (to PC)
        btn          : in  STD_LOGIC_VECTOR(1 downto 0);   -- btn(0) = reset
        led          : out STD_LOGIC_VECTOR(1 downto 0)    -- led(0) = RX, led(1) = TX
    );
end entity SOC;

architecture rtl of SOC is

    -- Baud rate constant fed to the UART, taken from the board package.
    constant BAUD : UNSIGNED(31 downto 0) := to_unsigned(BAUD_RATE, 32);

    -- Active-low reset.  BTN0 is active-high (pressed = '1'),
    -- so we invert it: BTN0 pressed → resetn = '0' → CPU resets.
    signal resetn : STD_LOGIC;

    -- ── CPU memory bus ────────────────────────────────────────────────────
    -- These signals are the wires connecting the CPU to memory and peripherals.
    -- The CPU drives memory_address, memory_write_data, memory_write_enable, memory_read_enable.
    -- Memory/peripherals drive memory_read_data back to the CPU.
    signal memory_address : STD_LOGIC_VECTOR(31 downto 0);   -- address the CPU is accessing
    signal memory_read_data : STD_LOGIC_VECTOR(31 downto 0);   -- data returned to the CPU
    signal memory_write_data : STD_LOGIC_VECTOR(31 downto 0);   -- data the CPU wants to write
    signal memory_write_enable   : STD_LOGIC;                       -- '1' = write this cycle
    signal memory_read_enable   : STD_LOGIC;                       -- '1' = read this cycle

    -- ── Address decode ────────────────────────────────────────────────────
    -- uart_select is '1' when the CPU is accessing the UART (bit 22 of address set).
    -- uart_select is '0' when the CPU is accessing Block RAM.
    signal uart_select : STD_LOGIC;

    -- ── Program memory (Block RAM) ────────────────────────────────────────
    -- Every FPGA contains dedicated on-chip memory blocks separate from the
    -- programmable logic cells. They are hardwired into the chip at manufacture
    -- and are fast, power-efficient, and ideal for program memory. Using them
    -- leaves the logic cells free for the CPU.
    --
    -- Different manufacturers call these blocks different things:
    --   Xilinx calls them Block RAM (Block RAM)
    --   Intel/Altera calls them M10K or M20K
    --   Lattice calls them EBR (Embedded Block RAM)
    -- The concept and behaviour are the same; only the name and available
    -- total size differ between vendors.
    --
    -- Currently 1024 words × 32 bits = 4 KB, set by BLOCK_RAM_WORDS in board/cmod_a7.vhd.
    -- The Artix-7 35T has 225 KB of block RAM in total; the current address decode
    -- supports up to 32768 words (128 KB). The right size depends on how large the
    -- M56 runtime grows — adjust BLOCK_RAM_WORDS once the firmware requirements are clearer.
    -- Note: large values significantly increase synthesis and place-and-route time.
    -- Keep BLOCK_RAM_WORDS small during development and grow it only when needed.
    --
    -- Initialised at synthesis time with the FIRMWARE constant from firmware_pkg.vhd,
    -- which asm.py generates by assembling echo.s.
    -- This means the program is baked into the bitstream — no SD card or loader needed.
    signal block_ram      : bram_init_t := FIRMWARE;
    signal block_ram_read_data : STD_LOGIC_VECTOR(31 downto 0);  -- data read out of Block RAM

    -- ── UART signals ──────────────────────────────────────────────────────
    signal uart_valid   : STD_LOGIC;                    -- '1' when a received byte is waiting
    signal uart_busy    : STD_LOGIC;                    -- '1' while transmitter is running
    signal uart_rx_data : STD_LOGIC_VECTOR(7 downto 0); -- the most recently received byte
    signal uart_rd      : STD_LOGIC;   -- pulse to acknowledge / clear the received byte
    signal uart_wr      : STD_LOGIC;   -- pulse to start transmitting a byte

    -- ── Interrupt signals ────────────────────────────────────────────────
    signal interrupt_pending  : STD_LOGIC;                      -- '1' when any source is requesting
    signal irq_status         : STD_LOGIC_VECTOR(31 downto 0); -- one bit per source; written to R13 on entry
    signal interrupts_enabled : STD_LOGIC;                     -- '1' when CPU will accept interrupts

begin

    -- ── Simple wiring ─────────────────────────────────────────────────────

    -- BTN0 pressed → reset active.  BTN0 released → CPU runs.
    resetn <= not btn(0);

    -- Address decode: is the CPU talking to the UART right now?
    uart_select <= memory_address(22);

    -- uart_rd fires when the CPU reads from the UART address.
    -- This tells the UART "byte has been consumed, you can accept the next one."
    -- Condition: reading (memory_read_enable=1) AND UART selected AND not a write.
    uart_rd <= memory_read_enable and uart_select and not memory_write_enable;

    -- uart_wr fires when the CPU writes to the UART address.
    -- This tells the UART transmitter "load this byte and start sending."
    uart_wr <= memory_write_enable and uart_select;

    -- ── Read-data mux ─────────────────────────────────────────────────────
    -- When the CPU reads, which device's data goes back?
    -- If the address is in Block RAM range: return block_ram_read_data.
    -- If the address is the UART:      return the status word.
    --
    -- The UART status word packs three things into 32 bits:
    --   bits 31..10 = 0 (unused)
    --   bit 9       = uart_busy  (TX is sending)
    --   bit 8       = uart_valid (RX has a byte waiting)
    --   bits 7..0   = uart_rx_data (the byte itself)
    memory_read_data <= block_ram_read_data when uart_select = '0' else
                (31 downto 10 => '0') & uart_busy & uart_valid & uart_rx_data;

    -- ── Block RAM ──────────────────────────────────────────────────────────────
    -- Synchronous (clocked) read and write.
    -- Reads have 1-cycle latency: address in on cycle N → data out on cycle N+1.
    -- The CPU's FETCH/EXEC timing is designed around this latency.
    -- Only accesses Block RAM when uart_select = '0' (address is in Block RAM range).
    process(clk)
    begin
        if rising_edge(clk) then
            if uart_select = '0' then
                if memory_write_enable = '1' then
                    -- Write: store memory_write_data at the addressed word.
                    -- Word address = byte address / 4 = bits 16..2 of memory_address.
                    block_ram(to_integer(unsigned(memory_address(16 downto 2)))) <= memory_write_data;
                end if;
                if memory_read_enable = '1' then
                    -- Read: output the word at the addressed location.
                    block_ram_read_data <= block_ram(to_integer(unsigned(memory_address(16 downto 2))));
                end if;
            end if;
        end if;
    end process;

    -- ── Interrupt controller ──────────────────────────────────────────────
    -- btn1 (BTN1, the button furthest from USB) fires interrupts.
    -- uart_valid is wired in but not yet an interrupt source — the firmware
    -- still polls the UART.  Both appear in irq_status so the handler can
    -- read R13 on entry and know exactly which source fired.
    irq0: entity work.interrupt_controller
        port map (
            clk                => clk,
            interrupts_enabled => interrupts_enabled,
            uart_rx_valid      => uart_valid,
            btn1               => btn(1),
            interrupt_pending  => interrupt_pending,
            irq_status         => irq_status
        );

    -- ── UART ──────────────────────────────────────────────────────────────
    -- uart handles everything to do with serial communication:
    --   - baud rate generation (counting clock cycles to get 115200 bps timing)
    --   - receiving: sampling the RX line, assembling 8 bits, asserting uart_valid
    --   - transmitting: shifting out 8 bits plus start/stop bits on the TX line
    uart0: entity work.uart
        generic map (CLOCKFREQUENCY => CLOCK_FREQUENCY)
        port map (
            clock   => clk,
            resetn  => resetn,
            baud    => BAUD,            -- 115200
            rx      => uart_rxd_in,     -- serial input from PC
            tx      => uart_txd_out,    -- serial output to PC
            rd      => uart_rd,         -- CPU says "I read the byte, clear valid"
            wr      => uart_wr,         -- CPU says "transmit this byte"
            valid   => uart_valid,      -- UART says "a byte is waiting"
            busy    => uart_busy,       -- UART says "currently transmitting"
            tx_data => memory_write_data(7 downto 0),  -- byte to send (low 8 bits of write data)
            rx_data => uart_rx_data     -- byte that was received
        );

    -- ── CPU ───────────────────────────────────────────────────────────────
    -- Wire the M56 CPU to the memory bus.
    -- Everything else (Block RAM, UART, address decode) is transparent to the CPU —
    -- it just sees one flat address space and reads/writes addresses.
    cpu0: entity work.m56_cpu
        port map (
            clk      => clk,
            resetn   => resetn,
            memory_address => memory_address,
            memory_read_data => memory_read_data,
            memory_write_data => memory_write_data,
            memory_write_enable   => memory_write_enable,
            memory_read_enable   => memory_read_enable,
            interrupt_request    => interrupt_pending,
            irq_status           => irq_status,
            interrupts_enabled   => interrupts_enabled
        );

    -- ── LEDs ──────────────────────────────────────────────────────────────
    -- Simple status indicators.
    -- LED0 flickers briefly each time a byte arrives (uart_valid goes high then low).
    -- LED1 stays lit for ~87 µs per transmitted byte (one 8N1 frame at 115200).
    led(0) <= uart_valid;
    led(1) <= uart_busy;

end architecture rtl;
