-- top.vhd — Titania M56 SoC top level for Cmod A7-35T
--
-- This is the "glue" file that connects the CPU, the program memory (BRAM),
-- and the UART together into a complete system.
--
-- ─── What lives here ─────────────────────────────────────────────────────────
--
--   CPU (cpu.vhd)       — executes M56 instructions
--   BRAM                — 1024 × 32-bit words of program/data memory,
--                         pre-loaded with echo.s firmware at synthesis time
--   UART (buart.vhd)    — sends and receives bytes over the USB-serial port
--
-- ─── Memory map ──────────────────────────────────────────────────────────────
--
--   Address bit 22 = 0  →  BRAM  (0x000000 – 0x3FFFFF)
--   Address bit 22 = 1  →  UART  (0x400000)
--
--   This is the simplest possible address decode: a single bit.
--   0x400000 in binary is 0100 0000 0000 0000 0000 0000 — bit 22 is set.
--   Any BRAM address has bit 22 = 0.
--
-- ─── UART register ───────────────────────────────────────────────────────────
--
--   Reading  0x400000 returns a 32-bit status word:
--     bit 9     = TX busy   (1 = transmitter is currently sending a byte)
--     bit 8     = RX valid  (1 = a byte has arrived and is waiting to be read)
--     bits 7..0 = received byte
--
--   Writing  0x400000 sends a byte:
--     bits 7..0 = byte to transmit
--
-- ─── Physical pins ───────────────────────────────────────────────────────────
--
--   BTN0 (nearest USB) = reset   — hold to reset CPU, release to run
--   LED0               = RX valid (briefly lights when a byte arrives)
--   LED1               = TX busy  (lights while the UART is sending)

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use work.firmware_pkg.ALL;   -- auto-generated by asm.py; contains FIRMWARE constant

entity SOC is
    port (
        clk          : in  STD_LOGIC;                      -- 12 MHz from Cmod A7
        uart_rxd_in  : in  STD_LOGIC;                      -- serial data in  (from PC)
        uart_txd_out : out STD_LOGIC;                      -- serial data out (to PC)
        btn          : in  STD_LOGIC_VECTOR(1 downto 0);   -- btn(0) = reset
        led          : out STD_LOGIC_VECTOR(1 downto 0)    -- led(0) = RX, led(1) = TX
    );
end entity SOC;

architecture rtl of SOC is

    -- Baud rate constant fed to the UART.  115200 bits per second.
    constant BAUD : UNSIGNED(31 downto 0) := to_unsigned(115200, 32);

    -- Active-low reset.  BTN0 is active-high (pressed = '1'),
    -- so we invert it: BTN0 pressed → resetn = '0' → CPU resets.
    signal resetn : STD_LOGIC;

    -- ── CPU memory bus ────────────────────────────────────────────────────
    -- These signals are the wires connecting the CPU to memory and peripherals.
    -- The CPU drives mem_addr, mem_wdat, mem_we, mem_re.
    -- Memory/peripherals drive mem_rdat back to the CPU.
    signal mem_addr : STD_LOGIC_VECTOR(31 downto 0);   -- address the CPU is accessing
    signal mem_rdat : STD_LOGIC_VECTOR(31 downto 0);   -- data returned to the CPU
    signal mem_wdat : STD_LOGIC_VECTOR(31 downto 0);   -- data the CPU wants to write
    signal mem_we   : STD_LOGIC;                       -- '1' = write this cycle
    signal mem_re   : STD_LOGIC;                       -- '1' = read this cycle

    -- ── Address decode ────────────────────────────────────────────────────
    -- sel_uart is '1' when the CPU is accessing the UART (bit 22 of address set).
    -- sel_uart is '0' when the CPU is accessing BRAM.
    signal sel_uart : STD_LOGIC;

    -- ── Program memory (BRAM) ─────────────────────────────────────────────
    -- 1024 words × 32 bits = 4 KB.
    -- Initialised at synthesis time with the FIRMWARE constant from firmware_pkg.vhd,
    -- which asm.py generates by assembling echo.s.
    -- This means the program is baked into the bitstream — no SD card or loader needed.
    signal bram      : bram_init_t := FIRMWARE;
    signal bram_rdat : STD_LOGIC_VECTOR(31 downto 0);  -- data read out of BRAM

    -- ── UART signals ──────────────────────────────────────────────────────
    signal uart_valid   : STD_LOGIC;                    -- '1' when a received byte is waiting
    signal uart_busy    : STD_LOGIC;                    -- '1' while transmitter is running
    signal uart_rx_data : STD_LOGIC_VECTOR(7 downto 0); -- the most recently received byte
    signal uart_rd      : STD_LOGIC;   -- pulse to acknowledge / clear the received byte
    signal uart_wr      : STD_LOGIC;   -- pulse to start transmitting a byte

begin

    -- ── Simple wiring ─────────────────────────────────────────────────────

    -- BTN0 pressed → reset active.  BTN0 released → CPU runs.
    resetn <= not btn(0);

    -- Address decode: is the CPU talking to the UART right now?
    sel_uart <= mem_addr(22);

    -- uart_rd fires when the CPU reads from the UART address.
    -- This tells the UART "byte has been consumed, you can accept the next one."
    -- Condition: reading (mem_re=1) AND UART selected AND not a write.
    uart_rd <= mem_re and sel_uart and not mem_we;

    -- uart_wr fires when the CPU writes to the UART address.
    -- This tells the UART transmitter "load this byte and start sending."
    uart_wr <= mem_we and sel_uart;

    -- ── Read-data mux ─────────────────────────────────────────────────────
    -- When the CPU reads, which device's data goes back?
    -- If the address is in BRAM range: return bram_rdat.
    -- If the address is the UART:      return the status word.
    --
    -- The UART status word packs three things into 32 bits:
    --   bits 31..10 = 0 (unused)
    --   bit 9       = uart_busy  (TX is sending)
    --   bit 8       = uart_valid (RX has a byte waiting)
    --   bits 7..0   = uart_rx_data (the byte itself)
    mem_rdat <= bram_rdat when sel_uart = '0' else
                (31 downto 10 => '0') & uart_busy & uart_valid & uart_rx_data;

    -- ── BRAM ──────────────────────────────────────────────────────────────
    -- Synchronous (clocked) read and write.
    -- Reads have 1-cycle latency: address in on cycle N → data out on cycle N+1.
    -- The CPU's FETCH/EXEC timing is designed around this latency.
    -- Only accesses BRAM when sel_uart = '0' (address is in BRAM range).
    process(clk)
    begin
        if rising_edge(clk) then
            if sel_uart = '0' then
                if mem_we = '1' then
                    -- Write: store mem_wdat at the addressed word.
                    -- Word address = byte address / 4 = bits 16..2 of mem_addr.
                    bram(to_integer(unsigned(mem_addr(16 downto 2)))) <= mem_wdat;
                end if;
                if mem_re = '1' then
                    -- Read: output the word at the addressed location.
                    bram_rdat <= bram(to_integer(unsigned(mem_addr(16 downto 2))));
                end if;
            end if;
        end if;
    end process;

    -- ── UART ──────────────────────────────────────────────────────────────
    -- buart handles everything to do with serial communication:
    --   - baud rate generation (counting clock cycles to get 115200 bps timing)
    --   - receiving: sampling the RX line, assembling 8 bits, asserting uart_valid
    --   - transmitting: shifting out 8 bits plus start/stop bits on the TX line
    uart0: entity work.buart
        generic map (CLKFREQ => 12_000_000)   -- tell it our clock speed
        port map (
            clk     => clk,
            resetn  => resetn,
            baud    => BAUD,            -- 115200
            rx      => uart_rxd_in,     -- serial input from PC
            tx      => uart_txd_out,    -- serial output to PC
            rd      => uart_rd,         -- CPU says "I read the byte, clear valid"
            wr      => uart_wr,         -- CPU says "transmit this byte"
            valid   => uart_valid,      -- UART says "a byte is waiting"
            busy    => uart_busy,       -- UART says "currently transmitting"
            tx_data => mem_wdat(7 downto 0),  -- byte to send (low 8 bits of write data)
            rx_data => uart_rx_data     -- byte that was received
        );

    -- ── CPU ───────────────────────────────────────────────────────────────
    -- Wire the M56 CPU to the memory bus.
    -- Everything else (BRAM, UART, address decode) is transparent to the CPU —
    -- it just sees one flat address space and reads/writes addresses.
    cpu0: entity work.m56_cpu
        port map (
            clk      => clk,
            resetn   => resetn,
            mem_addr => mem_addr,
            mem_rdat => mem_rdat,
            mem_wdat => mem_wdat,
            mem_we   => mem_we,
            mem_re   => mem_re
        );

    -- ── LEDs ──────────────────────────────────────────────────────────────
    -- Simple status indicators.
    -- LED0 flickers briefly each time a byte arrives (uart_valid goes high then low).
    -- LED1 stays lit for ~87 µs per transmitted byte (one 8N1 frame at 115200).
    led(0) <= uart_valid;
    led(1) <= uart_busy;

end architecture rtl;
