#!/usr/bin/env python3
"""
asm.py — two-pass assembler for the M56 CPU.

Handles the subset required for firmware/echo.s.
To be replaced by a self-hosted M56 assembler once the runtime exists.

Usage:
    python3 asm.py echo.s           — print address + word to stdout
    python3 asm.py echo.s echo.hex  — also write hex file (one word per line)
"""

import sys

OPCODES = {
    'mov': 0, 'mvb': 1, 'add': 2, 'sub': 3, 'and': 4,
    'orr': 5, 'xor': 6, 'not': 7, 'shf': 8, 'sar': 9,
    'jmp': 10, 'jpr': 11, 'wfi': 12, 'eai': 13, 'dai': 14, 'rti': 15,
}

# Instructions that take no operands — encoded with all fields zero.
ZERO_OPERAND = {'wfi', 'eai', 'dai', 'rti'}

COND = {'al': 0, 'z': 1, 'nz': 2, 'n': 3, 'nn': 4}


def reg(s):
    s = s.strip().upper()
    if not s.startswith('R'):
        raise ValueError(f"expected register, got '{s}'")
    return int(s[1:])


def imm(s):
    return int(s.strip().lstrip('#'), 0)


def encode(opcode, mode, r, imm19):
    return (opcode << 27) | (mode << 23) | (r << 19) | (imm19 & 0x7FFFF)


def clean(line):
    return line.split(';')[0].strip()


def split_ops(tail):
    return [o.strip() for o in tail.split(',')]


def assemble(source):
    lines = [clean(l) for l in source.splitlines()]

    # Pass 1 — assign an address to every label
    symbols = {}
    pc = 0
    for line in lines:
        if not line:
            continue
        if line.endswith(':'):
            symbols[line[:-1]] = pc
        else:
            pc += 4

    # Pass 2 — encode instructions
    words = []
    pc = 0
    for line in lines:
        if not line or line.endswith(':'):
            continue

        parts = line.split(None, 1)
        mn   = parts[0].lower()
        tail = parts[1] if len(parts) > 1 else ''
        ops  = split_ops(tail) if tail else []

        # --- zero-operand instructions: wfi, eai, dai, rti ---
        if mn in ZERO_OPERAND:
            words.append(encode(OPCODES[mn], 0, 0, 0))
            pc += 4
            continue

        # --- jpr[.cond] ---
        if mn.startswith('jpr'):
            cond_name = mn.split('.')[1] if '.' in mn else 'al'
            cond = COND[cond_name]
            if cond == 0:                   # jpr / jpr.al — no Rcmp operand
                rcmp  = 0
                label = ops[0]
            else:
                rcmp  = reg(ops[0])
                label = ops[1]
            offset = symbols[label] - (pc + 4)
            words.append(encode(11, cond, rcmp, offset))
            pc += 4
            continue

        # --- mov-h #imm, Rdst ---
        if mn == 'mov-h':
            words.append(encode(0, 1, reg(ops[1]), imm(ops[0])))
            pc += 4
            continue

        # --- mov (four forms, told apart by brackets) ---
        if mn == 'mov':
            src, dst = ops[0], ops[1]
            if src.startswith('['):                     # mov [Rsrc], Rdst
                words.append(encode(0, 3, reg(src.strip('[]')), reg(dst)))
            elif dst.startswith('['):                   # mov Rsrc, [Rdst]
                words.append(encode(0, 4, reg(src), reg(dst.strip('[]'))))
            else:                                       # mov Rsrc, Rdst
                words.append(encode(0, 2, reg(src), reg(dst)))
            pc += 4
            continue

        # --- ALU: add sub and orr xor (mode 0 = immediate, mode 2 = register) ---
        if mn in OPCODES:
            opc = OPCODES[mn]
            dst, src = ops[0], ops[1]
            if src.startswith('#') or src.lstrip('-+').isdigit():
                words.append(encode(opc, 0, reg(dst), imm(src)))
            else:
                words.append(encode(opc, 2, reg(dst), reg(src)))
            pc += 4
            continue

        raise ValueError(f"unknown mnemonic: {mn!r}  (line: {line!r})")

    return words


def vhdl_pkg(words, mem_words=1024):
    """VHDL package with sparse firmware initialisation for GHDL synth."""
    lines = [
        '-- firmware_pkg.vhd — generated by asm.py, do not edit',
        'library IEEE;',
        'use IEEE.STD_LOGIC_1164.ALL;',
        '',
        'package firmware_pkg is',
        f'    constant MEM_WORDS : integer := {mem_words};',
        f'    type bram_init_t is array(0 to MEM_WORDS-1) of std_logic_vector(31 downto 0);',
        '    constant FIRMWARE : bram_init_t := (',
    ]
    for i, w in enumerate(words):
        lines.append(f'        {i} => x"{w:08X}",')
    lines += [
        '        others => x"00000000"',
        '    );',
        'end package firmware_pkg;',
        '',
    ]
    return '\n'.join(lines)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(f'usage: {sys.argv[0]} input.s [output.hex]')

    with open(sys.argv[1]) as f:
        words = assemble(f.read())

    hex_lines = [f'{w:08X}' for w in words]

    if len(sys.argv) >= 3:
        base = sys.argv[2].removesuffix('.hex')
        with open(sys.argv[2], 'w') as f:
            f.write('\n'.join(hex_lines) + '\n')
        pkg_path = base + '_pkg.vhd'
        with open(pkg_path, 'w') as f:
            f.write(vhdl_pkg(words))
        print(f'wrote {len(words)} words → {sys.argv[2]}  and  {pkg_path}')

    for i, (w, h) in enumerate(zip(words, hex_lines)):
        print(f'0x{i*4:04X}  {h}')
